### ISSUE TITLE
Detection failing

### ISSUE THREAD

**Issue by jimmidyson** [whitel/vagrant-atomic#2]
Detection relies on `Atomic` being present in `/etc/os-release` but in both CentOS 7 & Fedora 21 Atomic images downloaded & updated to latest ostree for both, `/etc/os-release` doesn't contain `Atomic`. This check is at https://github.com/projectatomic/vagrant-atomic/blob/master/lib/vagrant-atomic/guest.rb#L7.

Not sure of a better way to do detection?

**Comment by humaton** [comment]
Can you please provide contents of /etc/os-release from those machines?

**Comment by jimmidyson** [comment]
This will is fixed by eb55c4bef9f7353f1976c4d0dae06c97f37e4340
