### ISSUE TITLE
Network configuration relies on biosdevname

### ISSUE THREAD

**Issue by jimmidyson** [whitel/vagrant-atomic#3]
In both CentOS 7 & Fedora 21 images downloaded from projectatomic.io & updated to latest ostrees, `/usr/sbin/biosdevname' doesn't exist, nor does`biosdevname` exist anywhere on the system.

Can we implement a way that works without `biosdevname` if it isn't present?

**Comment by jimmidyson** [comment]
Removing the network configuration steps in eb55c4bef9f7353f1976c4d0dae06c97f37e4340 won't actually solve this issue as Vagrant still tries to use biosdevname by default for Fedora21 Atomic.

**Comment by humaton** [comment]
@jimmidyson  what version of vagrant are you using? I am running 1.7.2 from upstream rpm and do not hit this issue with fedora atomic.

**Comment by jimmidyson** [comment]
1.7.2 with fedora 21 atomic with latest ostree updates. Problem is that
biosdevname doesn't exist in recent ostrees. Does this work with centos7
atomic? Perhaps I'll switch to that if so.

**Comment by humaton** [comment]
Hmm, can you please provide vagrant plugin list? 
For me it does work with both fedora/centos atomic hosts.

**Comment by jimmidyson** [comment]
I've built devel branch locally & installed:

sahara (0.0.17)
vagrant-atomic (0.0.3)
- Version Constraint: 0.0.3
  vagrant-libvirt (0.0.25)
  vagrant-mutate (0.3.2)
  vagrant-share (1.1.4, system)

Could you share your atomic base box(es) that you're using so I can see any
differences from my base box?

**Comment by humaton** [comment]
Sure 

https://atlas.hashicorp.com/humaton/boxes/fedora-atomic
https://atlas.hashicorp.com/humaton/boxes/centos-atomic

both are a bit old so you will need to run ostree upgrade.

**Comment by jimmidyson** [comment]
I've just tried it again with my base boxes & it's working. I must have made a mistake with plugin versions. Thanks for the help anyway!

Is there any chance of a 0.0.3 release so we can start using this?

**Comment by humaton** [comment]
Ok, I am closing this issue and releasing 0.0.3 to rubygems. It may take hour or so.

**Comment by jimmidyson** [comment]
Thanks!
