### ISSUE TITLE
Cleanup and submit to vagrant upstream

### ISSUE THREAD

**Issue by langdon** [whitel/vagrant-atomic#5]
1) remove vagrant-registration cap support and move it to vagrant-registration
2) general code clean up
3) merge to vagrant/plugins/guests
4) submit upstream

**Comment by strzibny** [comment]
I prepared the commit: https://github.com/strzibny/vagrant/commit/e9c4a1870e02d6cb546564e7bfc0debf04c39982

Is there anything missing?

**Comment by strzibny** [comment]
So it seems that having one Atomic guest might be problematic as we can inherit from Fedora, which would solve Fedora and RHEL guests, but would not help with CentOS ones.

**Comment by humaton** [comment]
How about using Flavors to identify specific atomic guest? example https://github.com/mitchellh/vagrant/blob/master/plugins/guests/redhat/cap/flavor.rb

**Comment by strzibny** [comment]
@humaton that's what I though too, perhaps Atomic should not be a guest on its own, but each guest would check for specific flavour. On the other hand I completely forgot that CentOS is identified as RHEL so one Atomic guest thats inherited from Fedora would actually work.

**Comment by strzibny** [comment]
Flavours approach might be nicer from a design POV, but copying all the if/else login in capabilities is what does not seem ideal. Thoughts?

**Comment by humaton** [comment]
Why would you copy anything? Flavor will return symbol like :centos_atomic or :rhel_atomic and we can incorporate this in the plugin logic...

**Comment by strzibny** [comment]
Incorporating this logic into capabilities is what would require to duplicate it (for Fedora and for Red Hat), because Red Hat capability should not expect to know anything about :fedora_atomic flavour.

**Comment by langdon** [comment]
So, the problem is, there isn't much reliable to distinguish between CentOS and RHEL. There continues to be talk on the CentOS devel mailing list about whether this should change or not, but clearly it is not something particularly reliable. Identifying "atomic-ness" was a matter of some debate (see tickets elsewhere) and the general proposal was to check capabilities. Does it make sense to not worry about this too much, as CentOS and RHEL should all have the same capabilities except registration? And, instead, leave the test for "registration support" in the registration plugin? I do think "atomic-ness" requires a new guest-type because of the differences in RO vs R/W filesystems and the use of package managers, but those things are less about specific difference between CentOS and RHEL (or even Fedora and RHEL to large extent). I also suspect further differences will appear which having a specific guest-type will alleviate later.

**Comment by strzibny** [comment]
I was thinking more about it and perhaps new guest type is appropriate (even debian vs debian8 is a new guest type now...). With current changes, everything should sort of work except the possibility of calling capabilities from FedoraGuest that would try to `yum install`. In my opinion, if we do AtomicGuest < FedoraGuest < RedHatGuest inheritance, we can easily change that in future to just inherit from Linux.

The capabilities that install something are:
- `nfs_client_install`
- `rsync_install`

Both `nfs-utils` and `rsync` are shipped in Atomic boxes so I don't see an issue here. Of course there are also provisioners, but we wouldn't be installing them on Atomic, this just won't be supported I guess. 

So...I would probably suggest to go with what we have now (it's ready, it works for what we need now) and we may revisit and make AtomicGuest inheret from plain LinuxGuest if necessary.

**Comment by humaton** [comment]
@strzibny  +1

**Comment by strzibny** [comment]
Here is the package review: https://bugzilla.redhat.com/show_bug.cgi?id=1224082. Once done, I submit this to upstream.

**Comment by voxik** [comment]
So what is the state here? The PR was merged apparently. So this should be probably closed and the whole project marked as obsolete ... I am going to add provides/obsoletes into Fedora Vagrant package and vagrant-atomic should be dropped from Fedora, right?

**Comment by strzibny** [comment]
Closing + README updated.

**Comment by voxik** [comment]
Thx 👍
